#	     _                 _     _
#	 ___| |_ __ _ _ __ ___| |__ (_)_ __
#	/ __| __/ _` | '__/ __| '_ \| | '_ \
#	\__ \ || (_| | |  \__ \ | | | | |_) |
#	|___/\__\__,_|_|  |___/_| |_|_| .__/
#	                              |_|
#	

# Don't print a new line at the start of the prompt
add_newline = true

# makes prompt a single line
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red)"

[cmd_duration]
format = " took [$duration]($style) "
style = "bold yellow"
disabled = true

# Disable the package module, hiding it from the prompt completely
[python]
disabled = false

[package]
disabled = false

[ruby]
disabled = false

[rust]
disabled = false

[nodejs]
disabled = false

[java]
disabled = false

[golang]
disabled = false

[aws]
disabled = false

